# Generated by Django 4.2.4 on 2023-09-19 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_ingredient_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemingredient',
            name='costRatio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
