# Generated by Django 4.2.4 on 2023-09-21 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_remove_itemingredient_costratio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
