# Generated by Django 4.2.4 on 2023-09-21 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_delete_item'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemWithIngredients',
            new_name='Item',
        ),
    ]
