# Generated by Django 4.2.4 on 2023-10-04 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_blacklisteditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='servings',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
