# Generated by Django 4.2.4 on 2023-10-09 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_ingredient_units'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(related_name='items', to='backend.tag'),
        ),
    ]
